src/Entity/Conducteur.php
<?php
// Définition de l'espace de nom
namespace App\Entity;
 
// Import des librairies
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use App\Repository\ConducteurRepository;
 
/**
 * Définition de la classe Conducteur liée à son Repository.
 * Un conducteur est défini par
 * - son identifiant entier co_id
 * - son nom (chaîne de 30 caractères) co_nom
 */
#[ORM\Entity(repositoryClass: ConducteurRepository::class)]
class Conducteur
{
    // --------------------------------------------------------------
    // Description des champs
    // --------------------------------------------------------------
 
    #[ORM\Id]
   #[ORM\GeneratedValue]
   #[ORM\Column(type: 'integer')]
   private ?int $co_id = null;
 
    #[ORM\Column(type:'string', length:30)]
   private ?string $co_nom = null;


    // Relation OneToMany avec l'entité Vehicule
    #[ORM\OneToMany(mappedBy: 've_conducteur', targetEntity: Vehicule::class)]
    private Collection $vehicules;
   
    // --------------------------------------------------------------
    // Methodes
    // --------------------------------------------------------------
 
    /**
     * Constructeur
     * Ici le constructeur est vide, il n'y a pas d'initialisation mais
     * on pourrait initialiser les deux champs co_id, co_nom
     */
    public function __construct()
    {
        $this->vehicules = new ArrayCollection();
    }
 
        /**
     * Obtenir la liste des véhicules associés au conducteur
     * 
     * @return Collection<int, Vehicule>
     */
    public function getVehicules(): Collection
    {
        return $this->vehicules;
    }
    /**
     * Obtenir la valeur du champ identifiant (co_id)
     */
    function getCoId() {
 
        return $this->co_id;
 
    }
 
    /**
     * Obtenir la valeur du champ nom (co_nom)
     */
    function getCoNom() {
 
        return $this->co_nom;
 
    }
 
    /**
     * Modifier la valeur du champ nom (co_nom)
     */
    function setCoNom($nom) {
 
        $this->co_nom = $nom;
   
        return $this;
   
    }
 
}
 
?>

src/Entity/Vehicule.php
<?php
namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use App\Repository\VehiculeRepository;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: VehiculeRepository::class)]
class Vehicule
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private ?int $ve_id = null;

    #[ORM\Column(type:'string', length:30)]
    #[Assert\NotBlank(message: "La marque ne peut pas être vide.")]
    private ?string $ve_marque = null;

    #[ORM\Column(type:'string', length:30)]
    #[Assert\NotBlank(message: "Le modèle ne peut pas être vide.")]
    private ?string $ve_modele = null;

    #[ORM\Column(type: "datetime", nullable: true)]
    #[Assert\NotBlank]
    #[Assert\NotNull]
    private $ve_date;

    #[ORM\ManyToOne(targetEntity: Conducteur::class, inversedBy: "vehicules")]
    #[ORM\JoinColumn(nullable: true, name: 've_co_id', referencedColumnName: 'co_id')]
    private ?Conducteur $ve_conducteur = null;

    #[ORM\OneToMany(mappedBy: 'eqve_vehicule', targetEntity: EquipementVehicule::class, cascade: ['persist', 'remove'])]
    private Collection $ve_equipement_vehicule;

    public function __construct()
    {
        $this->ve_date = new \DateTime();
        $this->ve_equipement_vehicule = new ArrayCollection(); // Initialisation de la collection
    }

    public function getVeId(): ?int
    {
        return $this->ve_id;
    }

    public function getVeMarque(): ?string
    {
        return $this->ve_marque;
    }

    public function setVeMarque(string $ve_marque): self
    {
        $this->ve_marque = $ve_marque;
        return $this;
    }

    public function getVeModele(): ?string
    {
        return $this->ve_modele;
    }

    public function setVeModele(string $ve_modele): self
    {
        $this->ve_modele = $ve_modele;
        return $this;
    }

    public function getVeDate(): ?\DateTimeInterface
    {
        return $this->ve_date;
    }

    public function setVeDate(\DateTimeInterface $ve_date): self
    {
        $this->ve_date = $ve_date;
        return $this;
    }

    public function getVeConducteur(): ?Conducteur
    {
        return $this->ve_conducteur;
    }

    public function setVeConducteur(?Conducteur $ve_conducteur): self
    {
        $this->ve_conducteur = $ve_conducteur;
        return $this;
    }

    public function getVeEquipementVehicule(): Collection
    {
        return $this->ve_equipement_vehicule;
    }

    public function addVeEquipementVehicule(EquipementVehicule $equipement_vehicule): self
    {
        if (!$this->ve_equipement_vehicule->contains($equipement_vehicule)) {
            $this->ve_equipement_vehicule[] = $equipement_vehicule;
            $equipement_vehicule->setEqVeVehicule($this);
        }

        return $this;
    }

    public function removeVeEquipementVehicule(EquipementVehicule $equipement_vehicule): self
    {
        if ($this->ve_equipement_vehicule->removeElement($equipement_vehicule)) {
            if ($equipement_vehicule->getEqVeVehicule() === $this) {
                $equipement_vehicule->setEqVeVehicule(null);
            }
        }

        return $this;
    }
}



?>

src/Form/ConducteurType.php
<?php
namespace App\Form;
 
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
 
// inclure la classe Conducteur
use App\Entity\Conducteur;
 
class ConducteurType extends AbstractType
{
    /**
     * Création d'un formulaire de saisie
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        // le conducteur ne contient qu'un champ nom de type string
        $builder
            ->add('co_nom', TextType::class, [
                'label' => 'Nom',
                'required' => true,
            ]);
           
            // ajout d'un gestionnaire d'évènement afin de modifier le nom du conducteur
            $builder->addEventListener(FormEvents::PRE_SUBMIT, function (FormEvent $event) {
                $data = $event->getData();
                $form = $event->getForm();
   
                // Si le nom existe alors mettre la première lettre en majuscule
                // et les autres lettres en minuscules
                if (isset($data['co_nom'])) {
                    $data['co_nom'] = ucfirst(strtolower($data['co_nom']));
                }
   
                // modifier l'évènement avec les nouvelles données
                $event->setData($data);
            });
    }
 
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Conducteur::class
        ]);
    }
}
?>

src/Controller/ConducteurController.php
<?php
// Fichier: src/Controller/ConducteurController.php

namespace App\Controller;
use App\Entity\Vehicule;
use App\Entity\Conducteur;
use App\Form\ConducteurType;
use App\Repository\ConducteurRepository;
use App\Repository\EquipementVehiculeRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\EntityManagerInterface;
use Psr\Log\LoggerInterface;

class ConducteurController extends AbstractController
{
    private $logger;
    private $entity_manager;
    private $repository;

    #[ORM\OneToMany(mappedBy: 've_conducteur', targetEntity: Vehicule::class)]
    private Collection $vehicules;

    public function __construct(LoggerInterface $logger, EntityManagerInterface $entity_manager)
    {
        $this->logger = $logger;
        $this->entity_manager = $entity_manager;
        $this->repository = $entity_manager->getRepository(Conducteur::class);
        $this->vehicules = new ArrayCollection(); // Initialisation de la collection
    }
 
    #[Route('/conducteur/lister', name: 'conducteur_lister')]
   public function lister(Request $request): Response
    {
        // obtenir la liste de tous les conducteurs triés par ordre alphabétique
        // croissant
        $liste_conducteurs = $this->repository->findAllOrderedByName();
       
        return $this->render("conducteur/lister.html.twig", [
            'liste_conducteurs' => $liste_conducteurs
        ]);
    }

   #[Route('/conducteur/supprimer/{id}', name: 'conducteur_supprimer')]
   public function supprimer($id): Response
   {
       // À partir du Repository, obtenir le conducteur grâce à son identifiant
       $conducteur = $this->repository->find($id);
       
       // Dans le cas où le conducteur n'aurait pas été trouvé, générer une exception
       if (!$conducteur) {
           throw $this->createNotFoundException('Aucun conducteur d\'identifiant ' . $id . ' n\'a été trouvé');
       }
       
       // Dissocier les véhicules associés au conducteur
       foreach ($conducteur->getVehicules() as $vehicule) {
           $vehicule->setve_conducteur(null);  // Dissocier le véhicule du conducteur
           $this->entity_manager->persist($vehicule);  // Persister la modification
       }
       
       // Maintenant, on peut supprimer le conducteur
       $this->entity_manager->remove($conducteur);
       $this->entity_manager->flush();
       
       // Rediriger vers l'affichage de la liste des conducteurs
       return $this->redirectToRoute('conducteur_lister');
   }
    #[Route('/conducteur/ajouter', name: 'conducteur_creer')]
    public function ajouter(Request $request): Response
     {
  
         $this->logger->info( 'Ajouter un conducteur' );                
        
         $message_erreur = "";
  
         // créer un conducteur dont les champs sont vides
         $conducteur = new Conducteur();
  
         // créer un formulaire qui prend en compte les données du conducteur
         $form = $this->createForm(ConducteurType::class, $conducteur);
  
         // récupération des données de la requête, notamment des
         // informations liées à la saisie d'un conducteur
         $form->handleRequest($request);
        
         // Si on vient de soumettre le formulaire et que les données
         // sont valides
         if ($form->isSubmitted() && $form->isValid()) {
  
             // Check if a driver with the same name already exists
             $conducteur_existant = $this->repository->findOneBy(['co_nom' => $conducteur->getCoNom()]);
            
             if ($conducteur_existant) {
        
                 $message_erreur = 'Il existe déjà un conducteur de même nom';
        
             } else {
                
                 // alors sauvegarder le conducteur (persist, flush)
                 $this->repository->save($conducteur, true);
  
                 // se rediriger vers l'affichage de la liste des conducteurs
                 // Attnetion on utilise le nom de la route 'conducteur_lister'
                 // et non 'conducteur/lister'
                 return $this->redirectToRoute('conducteur_lister');
             }
         }
  
             // sinon afficher la page contenant le formulaire d'ajout
         if (!empty($message_erreur)) $this->addFlash('error', $message_erreur);
            
         return $this->render('conducteur/ajouter.html.twig', [
             'form' => $form->createView(),
             'message_erreur' => $message_erreur
         ]);
     }
     /**
     * Modifier un conducteur étant donné son id
     */
    #[Route('/conducteur/modifier/{id}', name: 'conducteur_modifier')]
    public function modifier(Request $request, EntityManagerInterface $entityManager, int $id): Response
     {
  
         // à partir du Repository, obtenir le conducteur grâce à son identifiant
         $conducteur = $this->repository->find($id);
        
         // dans le cas où le conducteur n'aurait pas été trouvé, générer une exception
         if (!$conducteur) {
             throw $this->createNotFoundException('Acucun conducteur d\'identifiant ' . $id . ' n\'a été trouvé');
         }
  
         // créer le formulaire lié au conducteur
         $form = $this->createForm(ConducteurType::class, $conducteur);
  
         // récupération des données de la requête, notamment des
         // informations liées à la saisie d'un conducteur
         $form->handleRequest($request);
  
         // Si on vient de soumettre le formulaire et que les données
         // sont valies
         if ($form->isSubmitted() && $form->isValid()) {
  
             // alors sauvegarder le conducteur (persist, flush)
             $this->repository->save($conducteur, true);
  
             // se rediriger vers l'affichage de la liste des conducteurs
             // Attnetion on utilise le nom de la route 'conducteur_lister'
             // et non 'conducteur/lister'
             return $this->redirectToRoute('conducteur_lister');
         }
  
         // sinon afficher la page contenant le formulaire de modification
         return $this->render('conducteur/modifier.html.twig', [
             'form' => $form->createView(),
         ]);
  
     }
 
     // Méthode pour récupérer les véhicules associés
     public function getVehicules(): Collection
     {
         return $this->vehicules;
     }
     #[Route('/conducteur/{id}/vehicules', name: 'conducteur_vehicules')]
     public function voirVehicules(int $id, EquipementVehiculeRepository $equipementRepo): Response
     {
         $conducteur = $this->repository->find($id);
         if (!$conducteur) {
             throw $this->createNotFoundException("Conducteur non trouvé");
         }
     
         $vehicules = $conducteur->getVehicules();
     
         // Calculer le prix total des équipements du conducteur
         $equipements = $equipementRepo->findByConducteur($id);
         $prixTotal = array_reduce($equipements, fn($total, $eqVe) =>
             $total + ($eqVe->getEqVeQuantite() * $eqVe->getEqVeEquipement()->getEqPrix()), 0
         );
     
         return $this->render('conducteur/vehicules.html.twig', [
             'conducteur' => $conducteur,
             'vehicules' => $vehicules,
             'prix_total' => $prixTotal,
         ]);
     }
     

     #[Route('/conducteur/synthese', name: 'conducteur_synthese')]
public function synthese(EquipementVehiculeRepository $equipementVehiculeRepository): Response
{
    $conducteurs = $this->repository->findBy([], ['co_nom' => 'ASC']); // Trier les conducteurs
    $totalGeneralEquipements = 0;

    foreach ($conducteurs as $conducteur) {
        // Trier les véhicules du conducteur par date d'achat
        $vehicules = $conducteur->getVehicules()->toArray();
        usort($vehicules, fn($a, $b) => $a->getVeDate() <=> $b->getVeDate());

        foreach ($vehicules as $vehicule) {
            // Récupérer les équipements du véhicule
            $equipements = $equipementVehiculeRepository->findByVehicule($vehicule);
            $totalEquipements = 0;
            $detailsEquipements = [];

            foreach ($equipements as $equipementVehicule) {
                $quantite = $equipementVehicule->getEqVeQuantite();
                $prixUnitaire = $equipementVehicule->getEqVeEquipement()->getEqPrix();
                $libelle = $equipementVehicule->getEqVeEquipement()->getEqLibelle();
                $sousTotal = $quantite * $prixUnitaire;
                $totalEquipements += $sousTotal;

                $detailsEquipements[] = [
                    'libelle' => $libelle,
                    'quantite' => $quantite,
                    'prix' => $prixUnitaire,
                    'sousTotal' => $sousTotal,
                ];
            }

            // Injecter les infos préparées dans le véhicule (propriété dynamique pour la vue)
            $vehicule->totalEquipements = $totalEquipements;
            $vehicule->detailsEquipements = $detailsEquipements;

            // Ajouter au total général
            $totalGeneralEquipements += $totalEquipements;
        }

        // Injecter les véhicules triés dans le conducteur
        $conducteur->vehiculesTries = $vehicules;
    }

    return $this->render('conducteur/synthese.html.twig', [
        'conducteurs' => $conducteurs,
        'totalGeneralEquipements' => $totalGeneralEquipements,
    ]);
}

}

templates/conducteur/ajouter.html.twig
{% extends 'base.html.twig' %}

{% block css %}
    {{ parent() }}
    <style>
        div#conducteur_ve_date_help {
            margin-left: 150px;
            background: lightgray;
        }
    </style>
{% endblock %}

{% block main %}
<section class="container my-5">
    <h2 class="mb-4">Ajout d'un conducteur</h2>

    {# Formulaire d'ajout d'un conducteur avec Bootstrap #}
    {{ form_start(form, {'attr': {'class': 'needs-validation', 'novalidate': 'true'}}) }}
    
        <div class="mb-3">
            {{ form_label(form.co_nom, null, {'label_attr': {'class': 'form-label'}}) }}
            {{ form_widget(form.co_nom, {'attr': {'class': 'form-control'}}) }}
            {{ form_errors(form.co_nom) }}
        </div>
        
        {# Ajout d'autres champs du formulaire si nécessaires... #}
        {{ form_widget(form) }} 

        <button type="submit" class="btn btn-success">Ajouter</button>
    
    {{ form_end(form) }}
</section>

{# Displaying the error message in a JavaScript pop-up if there is one #}
{% if app.session.flashBag.has('error') %}
    <script type="text/javascript">
        alert("{{ app.session.flashBag.get('error')[0] }}");
    </script>
{% endif %}

{% endblock %}

templates/conducteur/lister.html.twig
{% extends 'base.html.twig' %}

{% block main %}
<section>
    <h2 class="my-4">🚗 Liste des Conducteurs</h2>

    <div class="d-flex justify-content-center mb-3">
        <a class="btn btn-primary me-2" href="/conducteur/ajouter">Ajouter</a>
        <a class="btn btn-danger" href="/conducteur/supprimer_tout"
           onclick="return confirm('Êtes-vous sûr de vouloir supprimer tous les conducteurs ?');">Tout Supprimer</a>
    </div>

    <input type="text" id="search-conducteur" class="form-control mb-2" placeholder="Rechercher un conducteur...">

    {% if liste_conducteurs is empty %}
        <p class="text-muted">Aucun conducteur trouvé.</p>
    {% else %}
        <div class="table-responsive">
            <table class="table table-hover table-striped table-bordered align-middle">
                <thead class="table-dark">
                    <tr>
                        <th>Id</th>
                        <th>Nom</th>
                        <th>Véhicules</th>
                        <th>Modifier</th>
                        <th>Supprimer</th>
                    </tr>
                </thead>
                <tbody>
                {% for e in liste_conducteurs %}
                    <tr class="conducteur-row" data-id="{{ e.CoId }}">
                        <td>{{ e.CoId }}</td>
                        <td>{{ e.CoNom }}</td>
                        <td class="text-center">
                           <a href="{{ path('conducteur_vehicules', {'id': e.CoId}) }}" class="btn btn-info btn-sm">Voir</a>


                        </td>
                        <td>
                            <button class="btn btn-link text-success"
                                onclick="return conducteur_modifier({{ e.CoId }});">
                                Modifier
                            </button>
                        </td>
                         <td>
                            <button class="btn btn-link text-danger"
                                onclick="return conducteur_supprimer({{ e.CoId }}, '{{ e.CoNom }}');">
                                Supprimer
                            </button>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
                                                <tfoot class="table-dark">
                    <tr>
                         <div class="mb-4">
                            <a href="{{ path('conducteur_synthese') }}" class="btn btn-info">📊 Voir Synthèse</a>
                            </div>
                    </tr>
               
            </table>
        </div>
    {% endif %}
</section>

<script>
document.addEventListener("DOMContentLoaded", function () {
    const searchInput = document.getElementById("search-conducteur");

    searchInput.addEventListener("input", function () {
        let filter = searchInput.value.toLowerCase();
        document.querySelectorAll(".conducteur-row").forEach(row => {
            let nom = row.querySelector("td:nth-child(2)").textContent.toLowerCase();
            row.style.display = nom.includes(filter) ? "" : "none";
        });
    });
});
</script>

{% endblock %}

templates/conducteur/modifier.html.twig
{% extends 'base.html.twig' %}

{% block main %}
<section class="container my-5">
    <h2 class="mb-4">Modification d'un conducteur</h2>

    {# Formulaire de modification du conducteur avec Bootstrap #}
    {{ form_start(form, {'attr': {'class': 'needs-validation', 'novalidate': 'true'}}) }}
        <div class="mb-3">
            {{ form_label(form.co_nom, null, {'label_attr': {'class': 'form-label'}}) }}
            {{ form_widget(form.co_nom, {'attr': {'class': 'form-control'}}) }}
            {{ form_errors(form.co_nom) }}
        </div>

        <button type="submit" class="btn btn-primary">Mettre à jour</button>
    {{ form_end(form) }}
</section>
{% endblock %}

templates/conducteur/syntese.html.twig
<div class="container my-4">
    {% for conducteur in conducteurs %}
        <div class="card mb-3">
            <div class="card-header">
                <h3 class="card-title">{{ conducteur.coNom }}</h3>
            </div>
            <div class="card-body">
                <ul class="list-group">
                    {% for vehicule in conducteur.vehiculesTries %}
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            {{ vehicule.veMarque }} {{ vehicule.veModele }}
                            <span class="badge bg-primary rounded-pill">{{ vehicule.totalEquipements }}€</span>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    {% endfor %}

    <div class="alert alert-info mt-4">
        <h4 class="alert-heading">Total général des équipements :</h4>
        <p class="lead">{{ totalGeneralEquipements }}€</p>
    </div>
</div>

templates/conducteur/synthese.html.twig
{% extends 'base.html.twig' %}

{% block main %}
<section class="container my-5">
    <h2 class="mb-4">📊 Tableau Synthétique des Conducteurs</h2>

    <table class="table table-striped table-bordered">
        <thead class="table-dark">
            <tr>
                <th>Conducteur</th>
                <th>Véhicule</th>
                <th>Date d'Achat</th>
                <th>Détail des Équipements</th>
                <th>Total Équipements (€)</th>
            </tr>
        </thead>
        <tbody>
            {% set somme_totale = 0 %}
            {% for conducteur in conducteurs %}
                {% set conducteur_span = conducteur.vehiculesTries|length %}
                {% if conducteur_span == 0 %}
                    <tr>
                        <td>{{ conducteur.CoNom }}</td>
                        <td colspan="4" class="text-center text-muted">Aucun véhicule</td>
                    </tr>
                {% else %}
                    {% for vehicule in conducteur.vehiculesTries %}
                        <tr>
                            {% if loop.first %}
                                <td rowspan="{{ conducteur_span }}">{{ conducteur.CoNom }}</td>
                            {% endif %}
                            <td>{{ vehicule.VeMarque }} - {{ vehicule.VeModele }}</td>
                            <td>{{ vehicule.VeDate|date('d/m/Y') }}</td>
                            <td>
                                {% if vehicule.detailsEquipements is not empty %}
                                    <table class="table table-sm table-bordered mb-0">
                                        <thead>
                                            <tr class="table-secondary">
                                                <th>Équipement</th>
                                                <th>Quantité</th>
                                                <th>Prix Unitaire (€)</th>
                                                <th>Sous-total (€)</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for equipement in vehicule.detailsEquipements %}
                                                <tr>
                                                    <td>{{ equipement.libelle }}</td>
                                                    <td>{{ equipement.quantite }}</td>
                                                    <td>{{ equipement.prix }}</td>
                                                    <td>{{ equipement.sousTotal }}</td>
                                                </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                {% else %}
                                    <span class="text-muted">Aucun équipement</span>
                                {% endif %}
                            </td>
                            <td>{{ vehicule.totalEquipements }} €</td>
                        </tr>
                        {% set somme_totale = somme_totale + vehicule.totalEquipements %}
                    {% endfor %}
                {% endif %}
            {% endfor %}
        </tbody>
        <tfoot>
            <tr class="table-warning">
                <td colspan="4" class="text-end"><strong>Somme totale des équipements :</strong></td>
                <td><strong>{{ somme_totale }} €</strong></td>
            </tr>
        </tfoot>
    </table>

    <a href="{{ path('conducteur_lister') }}" class="btn btn-primary">🔙 Retour</a>
</section>
{% endblock %}

templates/conducteur/vehicules.html.twig
{% extends 'base.html.twig' %}

{% block main %}
<section class="container my-5">
    <h2>🚗 Véhicules de {{ conducteur.CoNom }}</h2>

    {% if vehicules is empty %}
        <p class="text-muted">Aucun véhicule trouvé pour ce conducteur.</p>
    {% else %}
        <ul class="list-group">
            {% for v in vehicules %}
                <li class="list-group-item">
                    {{ v.VeMarque }} - {{ v.VeModele }} ({{ v.VeDate|date('d/m/Y') }})
                </li>
            {% endfor %}
        </ul>
    {% endif %}

    <div class="mt-4 alert alert-info">
        💰 Prix total des équipements : <strong>{{ prix_total }} €</strong>
    </div>

    <a href="{{ path('conducteur_lister') }}" class="btn btn-secondary">🔙 Retour</a>
</section>
{% endblock %}